name: Deploy next.js blog to github pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - id: check-env
        run: |
          echo GITHUB_OUTPUT = ${GITHUB_OUTPUT}
          echo github.workspace = ${{ github.workspace }}
          echo "name=seun" >> ${GITHUB_OUTPUT}
          echo ${{ steps.check-env.outputs.name }}
